/* SPDX-License-Identifier: Apache-2.0 */
#include "ir.h"

#ifdef CONFIG_APP_IR

#include "nec.h"

#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/drivers/pwm.h>
#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(ir, LOG_LEVEL_INF);

/*
 * IR TX over the LEDC PWM carrier (G46). Zephyr 4.4 has no ESP32 RMT driver, so
 * the ~38 kHz carrier is generated by LEDC and the NEC envelope is produced by
 * gating the carrier duty between ~1/3 (mark) and 0 (space), with k_busy_wait()
 * between transitions. RX (MCPWM capture + decode) is added in IR-P4.
 */
static const struct device *const ledc = DEVICE_DT_GET(DT_NODELABEL(ledc0));

#define IR_TX_CHANNEL        0U
#define IR_CARRIER_PERIOD_NS 26316U /* ~38.0 kHz */
#define IR_CARRIER_PULSE_NS  8772U  /* ~1/3 duty */

/* The demo IR page transmits this fixed NEC code on entry. */
#define IR_TEST_ADDR 0x04U
#define IR_TEST_CMD  0x1BU

static bool ready;
static uint32_t tx_count;

static inline void carrier_on(void)
{
	(void)pwm_set(ledc, IR_TX_CHANNEL, IR_CARRIER_PERIOD_NS,
		      IR_CARRIER_PULSE_NS, 0);
}

static inline void carrier_off(void)
{
	(void)pwm_set(ledc, IR_TX_CHANNEL, IR_CARRIER_PERIOD_NS, 0U, 0);
}

static inline void mark(uint32_t us)
{
	carrier_on();
	k_busy_wait(us);
}

static inline void space(uint32_t us)
{
	carrier_off();
	k_busy_wait(us);
}

int ir_init(void)
{
	if (!device_is_ready(ledc)) {
		LOG_ERR("LEDC (IR TX) not ready");
		return -ENODEV;
	}

	carrier_off(); /* idle low (LED off) */
	ready = true;
	LOG_INF("ir_init OK (TX on LEDC ch%u, ~38 kHz carrier)", IR_TX_CHANNEL);
	return 0;
}

bool ir_ready(void)
{
	return ready;
}

void ir_tx_nec(uint8_t addr, uint8_t cmd)
{
	uint32_t frame;

	if (!ready) {
		return;
	}

	frame = nec_encode(addr, cmd);

	/*
	 * Hold off thread preemption for the frame (~tens of ms, like the audio
	 * beep) so a context switch cannot stretch a mark/space. Interrupts still
	 * run; NEC's ~+/-20% tolerance on the 560 us base unit absorbs that
	 * jitter. k_busy_wait() spins (no scheduling) so this is safe under the
	 * scheduler lock.
	 */
	k_sched_lock();

	mark(NEC_LEADER_MARK_US);
	space(NEC_LEADER_SPACE_US);
	for (uint32_t i = 0; i < 32U; i++) {
		mark(NEC_BIT_MARK_US);
		space(((frame >> i) & 1U) ? NEC_ONE_SPACE_US : NEC_ZERO_SPACE_US);
	}
	mark(NEC_STOP_MARK_US);
	carrier_off();

	k_sched_unlock();

	tx_count++;
	LOG_INF("ir_tx addr=0x%02x cmd=0x%02x (#%u)", addr, cmd,
		(unsigned int)tx_count);
}

void ir_tx_test(void)
{
	ir_tx_nec(IR_TEST_ADDR, IR_TEST_CMD);
}

uint32_t ir_tx_count(void)
{
	return tx_count;
}

#endif /* CONFIG_APP_IR */
